name: Simple Input + Needs

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your age'
        required: true

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      uage: ${{ steps.set-age.outputs.age }}
    steps:
      - id: set-age
        run: echo "age=${{ github.event.inputs.age }}" >> $GITHUB_OUTPUT

  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        run: echo "Hello, ${{ needs.first.outputs.uage }}!"
